// pages/tag/tag.ts
Page({

  /**
   * 页面的初始数据
   */
  data: {
    tagListKey:[
      "all","fixedWidth","adaptiveWidth","icon"
    ],
    tagList:{
      "all":[
        {
          color:"Background-Medium_Foreground-High",
          showIcon:true,
          iconPath:"setting_gray_line",
          fixedWidth:true,
          fixedLabel:"22",
          adaptiveWidth:true,
          adaptiveLabel:"这是一个不定长文本区",
          closeable:true
        },
        {
          color:"Background-Medium_Foreground-Medium",
          showIcon:true,
          iconPath:"setting_gray_line",
          fixedWidth:true,
          fixedLabel:"22",
          adaptiveWidth:true,
          adaptiveLabel:"这是一个不定长文本区",
          closeable:true
        },
        {
          color:"Background-Primary_Foreground-Primary",
          showIcon:true,
          iconPath:"setting_gray_line",
          fixedWidth:true,
          fixedLabel:"22",
          adaptiveWidth:true,
          adaptiveLabel:"这是一个不定长文本区",
          closeable:true
        },
        {
          color:"Background-Secondary_Foreground-Secondary",
          showIcon:true,
          iconPath:"setting_gray_line",
          fixedWidth:true,
          fixedLabel:"22",
          adaptiveWidth:true,
          adaptiveLabel:"这是一个不定长文本区",
          closeable:true
        },
        {
          color:"Background-Error_Foreground-Error",
          showIcon:true,
          iconPath:"setting_gray_line",
          fixedWidth:true,
          fixedLabel:"22",
          adaptiveWidth:true,
          adaptiveLabel:"这是一个不定长文本区",
          closeable:true
        },
        {
          color:"Background-Tertiary_Foreground-Tertiary",
          showIcon:true,
          iconPath:"setting_gray_line",
          fixedWidth:true,
          fixedLabel:"22",
          adaptiveWidth:true,
          adaptiveLabel:"这是一个不定长文本区",
          closeable:true
        },
        {
          color:"Foreground-Primary_Foreground-Low",
          showIcon:true,
          iconPath:"setting_gray_line",
          fixedWidth:true,
          fixedLabel:"22",
          adaptiveWidth:true,
          adaptiveLabel:"这是一个不定长文本区",
          closeable:true
        },
        {
          color:"Foreground-Secondary_Foreground-Low",
          showIcon:true,
          iconPath:"setting_gray_line",
          fixedWidth:true,
          fixedLabel:"22",
          adaptiveWidth:true,
          adaptiveLabel:"这是一个不定长文本区",
          closeable:true
        },
        {
          color:"Foreground-Error_Foreground-Low",
          showIcon:true,
          iconPath:"setting_gray_line",
          fixedWidth:true,
          fixedLabel:"22",
          adaptiveWidth:true,
          adaptiveLabel:"这是一个不定长文本区",
          closeable:true
        },
        {
          color:"Foreground-Tertiary_Foreground-Low",
          showIcon:true,
          iconPath:"setting_gray_line",
          fixedWidth:true,
          fixedLabel:"22",
          adaptiveWidth:true,
          adaptiveLabel:"这是一个不定长文本区",
          closeable:true
        },
      ],
      "fixedWidth":[
        // 图标true 固定宽度true 自适应宽度false 关闭true
        {
          color:"Background-Medium_Foreground-High",
          showIcon:true,
          iconPath:"setting_gray_line",
          fixedWidth:true,
          fixedLabel:"22",
          adaptiveWidth:false,
          adaptiveLabel:"这是一个不定长文本区",
          closeable:true
        },
        {
          color:"Background-Medium_Foreground-Medium",
          showIcon:true,
          iconPath:"setting_gray_line",
          fixedWidth:true,
          fixedLabel:"22",
          adaptiveWidth:false,
          adaptiveLabel:"这是一个不定长文本区",
          closeable:true
        },
        {
          color:"Background-Primary_Foreground-Primary",
          showIcon:true,
          iconPath:"setting_gray_line",
          fixedWidth:true,
          fixedLabel:"22",
          adaptiveWidth:false,
          adaptiveLabel:"这是一个不定长文本区",
          closeable:true
        },
        {
          color:"Background-Secondary_Foreground-Secondary",
          showIcon:true,
          iconPath:"setting_gray_line",
          fixedWidth:true,
          fixedLabel:"22",
          adaptiveWidth:false,
          adaptiveLabel:"这是一个不定长文本区",
          closeable:true
        },
        {
          color:"Background-Error_Foreground-Error",
          showIcon:true,
          iconPath:"setting_gray_line",
          fixedWidth:true,
          fixedLabel:"22",
          adaptiveWidth:false,
          adaptiveLabel:"这是一个不定长文本区",
          closeable:true
        },
        {
          color:"Background-Tertiary_Foreground-Tertiary",
          showIcon:true,
          iconPath:"setting_gray_line",
          fixedWidth:true,
          fixedLabel:"22",
          adaptiveWidth:false,
          adaptiveLabel:"这是一个不定长文本区",
          closeable:true
        },
        {
          color:"Foreground-Primary_Foreground-Low",
          showIcon:true,
          iconPath:"setting_gray_line",
          fixedWidth:true,
          fixedLabel:"22",
          adaptiveWidth:false,
          adaptiveLabel:"这是一个不定长文本区",
          closeable:true
        },
        {
          color:"Foreground-Secondary_Foreground-Low",
          showIcon:true,
          iconPath:"setting_gray_line",
          fixedWidth:true,
          fixedLabel:"22",
          adaptiveWidth:false,
          adaptiveLabel:"这是一个不定长文本区",
          closeable:true
        },
        {
          color:"Foreground-Error_Foreground-Low",
          showIcon:true,
          iconPath:"setting_gray_line",
          fixedWidth:true,
          fixedLabel:"22",
          adaptiveWidth:false,
          adaptiveLabel:"这是一个不定长文本区",
          closeable:true
        },
        {
          color:"Foreground-Tertiary_Foreground-Low",
          showIcon:true,
          iconPath:"setting_gray_line",
          fixedWidth:true,
          fixedLabel:"22",
          adaptiveWidth:false,
          adaptiveLabel:"这是一个不定长文本区",
          closeable:true
        },
        // 图标false 固定宽度true 自适应宽度false  关闭true
        {
          color:"Background-Medium_Foreground-High",
          showIcon:false,
          iconPath:"setting_gray_line",
          fixedWidth:true,
          fixedLabel:"22",
          adaptiveWidth:false,
          adaptiveLabel:"这是一个不定长文本区",
          closeable:true
        },
        {
          color:"Background-Medium_Foreground-Medium",
          showIcon:false,
          iconPath:"setting_gray_line",
          fixedWidth:true,
          fixedLabel:"22",
          adaptiveWidth:false,
          adaptiveLabel:"这是一个不定长文本区",
          closeable:true
        },
        {
          color:"Foreground-Primary_Foreground-Low",
          showIcon:false,
          iconPath:"setting_gray_line",
          fixedWidth:true,
          fixedLabel:"22",
          adaptiveWidth:false,
          adaptiveLabel:"这是一个不定长文本区",
          closeable:true
        },
        {
          color:"Background-Secondary_Foreground-Secondary",
          showIcon:false,
          iconPath:"setting_gray_line",
          fixedWidth:true,
          fixedLabel:"22",
          adaptiveWidth:false,
          adaptiveLabel:"这是一个不定长文本区",
          closeable:true
        },
        {
          color:"Background-Error_Foreground-Error",
          showIcon:false,
          iconPath:"setting_gray_line",
          fixedWidth:true,
          fixedLabel:"22",
          adaptiveWidth:false,
          adaptiveLabel:"这是一个不定长文本区",
          closeable:true
        },
        {
          color:"Background-Tertiary_Foreground-Tertiary",
          showIcon:false,
          iconPath:"setting_gray_line",
          fixedWidth:true,
          fixedLabel:"22",
          adaptiveWidth:false,
          adaptiveLabel:"这是一个不定长文本区",
          closeable:true
        },
        {
          color:"Foreground-Primary_Foreground-Low",
          showIcon:false,
          iconPath:"setting_gray_line",
          fixedWidth:true,
          fixedLabel:"22",
          adaptiveWidth:false,
          adaptiveLabel:"这是一个不定长文本区",
          closeable:true
        },
        {
          color:"Foreground-Secondary_Foreground-Low",
          showIcon:false,
          iconPath:"setting_gray_line",
          fixedWidth:true,
          fixedLabel:"22",
          adaptiveWidth:false,
          adaptiveLabel:"这是一个不定长文本区",
          closeable:true
        },
        {
          color:"Foreground-Error_Foreground-Low",
          showIcon:false,
          iconPath:"setting_gray_line",
          fixedWidth:true,
          fixedLabel:"22",
          adaptiveWidth:false,
          adaptiveLabel:"这是一个不定长文本区",
          closeable:true
        },
        {
          color:"Foreground-Tertiary_Foreground-Low",
          showIcon:false,
          iconPath:"setting_gray_line",
          fixedWidth:true,
          fixedLabel:"22",
          adaptiveWidth:false,
          adaptiveLabel:"这是一个不定长文本区",
          closeable:true
        },
        // 图标true 固定宽度true 自适应宽度false  关闭false
        {
          color:"Background-Medium_Foreground-High",
          showIcon:true,
          iconPath:"setting_gray_line",
          fixedWidth:true,
          fixedLabel:"22",
          adaptiveWidth:false,
          adaptiveLabel:"这是一个不定长文本区",
          closeable:false
        },
        {
          color:"Background-Medium_Foreground-Medium",
          showIcon:true,
          iconPath:"setting_gray_line",
          fixedWidth:true,
          fixedLabel:"22",
          adaptiveWidth:false,
          adaptiveLabel:"这是一个不定长文本区",
          closeable:false
        },
        {
          color:"Foreground-Primary_Foreground-Low",
          showIcon:true,
          iconPath:"setting_gray_line",
          fixedWidth:true,
          fixedLabel:"22",
          adaptiveWidth:false,
          adaptiveLabel:"这是一个不定长文本区",
          closeable:false
        },
        {
          color:"Background-Secondary_Foreground-Secondary",
          showIcon:true,
          iconPath:"setting_gray_line",
          fixedWidth:true,
          fixedLabel:"22",
          adaptiveWidth:false,
          adaptiveLabel:"这是一个不定长文本区",
          closeable:false
        },
        {
          color:"Background-Error_Foreground-Error",
          showIcon:true,
          iconPath:"setting_gray_line",
          fixedWidth:true,
          fixedLabel:"22",
          adaptiveWidth:false,
          adaptiveLabel:"这是一个不定长文本区",
          closeable:false
        },
        {
          color:"Background-Tertiary_Foreground-Tertiary",
          showIcon:true,
          iconPath:"setting_gray_line",
          fixedWidth:true,
          fixedLabel:"22",
          adaptiveWidth:false,
          adaptiveLabel:"这是一个不定长文本区",
          closeable:false
        },
        {
          color:"Foreground-Primary_Foreground-Low",
          showIcon:true,
          iconPath:"setting_gray_line",
          fixedWidth:true,
          fixedLabel:"22",
          adaptiveWidth:false,
          adaptiveLabel:"这是一个不定长文本区",
          closeable:false
        },
        {
          color:"Foreground-Secondary_Foreground-Low",
          showIcon:true,
          iconPath:"setting_gray_line",
          fixedWidth:true,
          fixedLabel:"22",
          adaptiveWidth:false,
          adaptiveLabel:"这是一个不定长文本区",
          closeable:false
        },
        {
          color:"Foreground-Error_Foreground-Low",
          showIcon:true,
          iconPath:"setting_gray_line",
          fixedWidth:true,
          fixedLabel:"22",
          adaptiveWidth:false,
          adaptiveLabel:"这是一个不定长文本区",
          closeable:false
        },
        {
          color:"Foreground-Tertiary_Foreground-Low",
          showIcon:true,
          iconPath:"setting_gray_line",
          fixedWidth:true,
          fixedLabel:"22",
          adaptiveWidth:false,
          adaptiveLabel:"这是一个不定长文本区",
          closeable:false
        },
        // 图标false 固定宽度true 自适应宽度false  关闭false
        {
          color:"Background-Medium_Foreground-High",
          showIcon:false,
          iconPath:"setting_gray_line",
          fixedWidth:true,
          fixedLabel:"22",
          adaptiveWidth:false,
          adaptiveLabel:"这是一个不定长文本区",
          closeable:false
        },
        {
          color:"Background-Medium_Foreground-Medium",
          showIcon:false,
          iconPath:"setting_gray_line",
          fixedWidth:true,
          fixedLabel:"22",
          adaptiveWidth:false,
          adaptiveLabel:"这是一个不定长文本区",
          closeable:false
        },
        {
          color:"Foreground-Primary_Foreground-Low",
          showIcon:false,
          iconPath:"setting_gray_line",
          fixedWidth:true,
          fixedLabel:"22",
          adaptiveWidth:false,
          adaptiveLabel:"这是一个不定长文本区",
          closeable:false
        },
        {
          color:"Background-Secondary_Foreground-Secondary",
          showIcon:false,
          iconPath:"setting_gray_line",
          fixedWidth:true,
          fixedLabel:"22",
          adaptiveWidth:false,
          adaptiveLabel:"这是一个不定长文本区",
          closeable:false
        },
        {
          color:"Background-Error_Foreground-Error",
          showIcon:false,
          iconPath:"setting_gray_line",
          fixedWidth:true,
          fixedLabel:"22",
          adaptiveWidth:false,
          adaptiveLabel:"这是一个不定长文本区",
          closeable:false
        },
        {
          color:"Background-Tertiary_Foreground-Tertiary",
          showIcon:false,
          iconPath:"setting_gray_line",
          fixedWidth:true,
          fixedLabel:"22",
          adaptiveWidth:false,
          adaptiveLabel:"这是一个不定长文本区",
          closeable:false
        },
        {
          color:"Foreground-Primary_Foreground-Low",
          showIcon:false,
          iconPath:"setting_gray_line",
          fixedWidth:true,
          fixedLabel:"22",
          adaptiveWidth:false,
          adaptiveLabel:"这是一个不定长文本区",
          closeable:false
        },
        {
          color:"Foreground-Secondary_Foreground-Low",
          showIcon:false,
          iconPath:"setting_gray_line",
          fixedWidth:true,
          fixedLabel:"22",
          adaptiveWidth:false,
          adaptiveLabel:"这是一个不定长文本区",
          closeable:false
        },
        {
          color:"Foreground-Error_Foreground-Low",
          showIcon:false,
          iconPath:"setting_gray_line",
          fixedWidth:true,
          fixedLabel:"22",
          adaptiveWidth:false,
          adaptiveLabel:"这是一个不定长文本区",
          closeable:false
        },
        {
          color:"Foreground-Tertiary_Foreground-Low",
          showIcon:false,
          iconPath:"setting_gray_line",
          fixedWidth:true,
          fixedLabel:"22",
          adaptiveWidth:false,
          adaptiveLabel:"这是一个不定长文本区",
          closeable:false
        },
      ],
      "adaptiveWidth":[
        // 图标true 固定宽度false 自适应宽度true  关闭true
        {
          color:"Background-Medium_Foreground-High",
          showIcon:true,
          iconPath:"setting_gray_line",
          fixedWidth:false,
          fixedLabel:"22",
          adaptiveWidth:true,
          adaptiveLabel:"这是一个不定长文本区",
          closeable:true
        },
        {
          color:"Background-Medium_Foreground-Medium",
          showIcon:true,
          iconPath:"setting_gray_line",
          fixedWidth:false,
          fixedLabel:"22",
          adaptiveWidth:true,
          adaptiveLabel:"这是一个不定长文本区",
          closeable:true
        },
        {
          color:"Background-Primary_Foreground-Primary",
          showIcon:true,
          iconPath:"setting_gray_line",
          fixedWidth:false,
          fixedLabel:"22",
          adaptiveWidth:true,
          adaptiveLabel:"这是一个不定长文本区",
          closeable:true
        },
        {
          color:"Background-Secondary_Foreground-Secondary",
          showIcon:true,
          iconPath:"setting_gray_line",
          fixedWidth:false,
          fixedLabel:"22",
          adaptiveWidth:true,
          adaptiveLabel:"这是一个不定长文本区",
          closeable:true
        },
        {
          color:"Background-Error_Foreground-Error",
          showIcon:true,
          iconPath:"setting_gray_line",
          fixedWidth:false,
          fixedLabel:"22",
          adaptiveWidth:true,
          adaptiveLabel:"这是一个不定长文本区",
          closeable:true
        },
        {
          color:"Background-Tertiary_Foreground-Tertiary",
          showIcon:true,
          iconPath:"setting_gray_line",
          fixedWidth:false,
          fixedLabel:"22",
          adaptiveWidth:true,
          adaptiveLabel:"这是一个不定长文本区",
          closeable:true
        },
        {
          color:"Foreground-Primary_Foreground-Low",
          showIcon:true,
          iconPath:"setting_gray_line",
          fixedWidth:false,
          fixedLabel:"22",
          adaptiveWidth:true,
          adaptiveLabel:"这是一个不定长文本区",
          closeable:true
        },
        {
          color:"Foreground-Secondary_Foreground-Low",
          showIcon:true,
          iconPath:"setting_gray_line",
          fixedWidth:false,
          fixedLabel:"22",
          adaptiveWidth:true,
          adaptiveLabel:"这是一个不定长文本区",
          closeable:true
        },
        {
          color:"Foreground-Error_Foreground-Low",
          showIcon:true,
          iconPath:"setting_gray_line",
          fixedWidth:false,
          fixedLabel:"22",
          adaptiveWidth:true,
          adaptiveLabel:"这是一个不定长文本区",
          closeable:true
        },
        {
          color:"Foreground-Tertiary_Foreground-Low",
          showIcon:true,
          iconPath:"setting_gray_line",
          fixedWidth:false,
          fixedLabel:"22",
          adaptiveWidth:true,
          adaptiveLabel:"这是一个不定长文本区",
          closeable:true
        },
        // 图标false 固定宽度false 自适应宽度true  关闭true
        {
          color:"Background-Medium_Foreground-High",
          showIcon:false,
          iconPath:"setting_gray_line",
          fixedWidth:false,
          fixedLabel:"22",
          adaptiveWidth:true,
          adaptiveLabel:"这是一个不定长文本区",
          closeable:true
        },
        {
          color:"Background-Medium_Foreground-Medium",
          showIcon:false,
          iconPath:"setting_gray_line",
          fixedWidth:false,
          fixedLabel:"22",
          adaptiveWidth:true,
          adaptiveLabel:"这是一个不定长文本区",
          closeable:true
        },
        {
          color:"Foreground-Primary_Foreground-Low",
          showIcon:false,
          iconPath:"setting_gray_line",
          fixedWidth:false,
          fixedLabel:"22",
          adaptiveWidth:true,
          adaptiveLabel:"这是一个不定长文本区",
          closeable:true
        },
        {
          color:"Background-Secondary_Foreground-Secondary",
          showIcon:false,
          iconPath:"setting_gray_line",
          fixedWidth:false,
          fixedLabel:"22",
          adaptiveWidth:true,
          adaptiveLabel:"这是一个不定长文本区",
          closeable:true
        },
        {
          color:"Background-Error_Foreground-Error",
          showIcon:false,
          iconPath:"setting_gray_line",
          fixedWidth:false,
          fixedLabel:"22",
          adaptiveWidth:true,
          adaptiveLabel:"这是一个不定长文本区",
          closeable:true
        },
        {
          color:"Background-Tertiary_Foreground-Tertiary",
          showIcon:false,
          iconPath:"setting_gray_line",
          fixedWidth:false,
          fixedLabel:"22",
          adaptiveWidth:true,
          adaptiveLabel:"这是一个不定长文本区",
          closeable:true
        },
        {
          color:"Foreground-Primary_Foreground-Low",
          showIcon:false,
          iconPath:"setting_gray_line",
          fixedWidth:false,
          fixedLabel:"22",
          adaptiveWidth:true,
          adaptiveLabel:"这是一个不定长文本区",
          closeable:true
        },
        {
          color:"Foreground-Secondary_Foreground-Low",
          showIcon:false,
          iconPath:"setting_gray_line",
          fixedWidth:false,
          fixedLabel:"22",
          adaptiveWidth:true,
          adaptiveLabel:"这是一个不定长文本区",
          closeable:true
        },
        {
          color:"Foreground-Error_Foreground-Low",
          showIcon:false,
          iconPath:"setting_gray_line",
          fixedWidth:false,
          fixedLabel:"22",
          adaptiveWidth:true,
          adaptiveLabel:"这是一个不定长文本区",
          closeable:true
        },
        {
          color:"Foreground-Tertiary_Foreground-Low",
          showIcon:false,
          iconPath:"setting_gray_line",
          fixedWidth:false,
          fixedLabel:"22",
          adaptiveWidth:true,
          adaptiveLabel:"这是一个不定长文本区",
          closeable:true
        },
        // 图标true 固定宽度false 自适应宽度true  关闭false
        {
          color:"Background-Medium_Foreground-High",
          showIcon:true,
          iconPath:"setting_gray_line",
          fixedWidth:false,
          fixedLabel:"22",
          adaptiveWidth:true,
          adaptiveLabel:"这是一个不定长文本区",
          closeable:false
        },
        {
          color:"Background-Medium_Foreground-Medium",
          showIcon:true,
          iconPath:"setting_gray_line",
          fixedWidth:false,
          fixedLabel:"22",
          adaptiveWidth:true,
          adaptiveLabel:"这是一个不定长文本区",
          closeable:false
        },
        {
          color:"Foreground-Primary_Foreground-Low",
          showIcon:true,
          iconPath:"setting_gray_line",
          fixedWidth:false,
          fixedLabel:"22",
          adaptiveWidth:true,
          adaptiveLabel:"这是一个不定长文本区",
          closeable:false
        },
        {
          color:"Background-Secondary_Foreground-Secondary",
          showIcon:true,
          iconPath:"setting_gray_line",
          fixedWidth:false,
          fixedLabel:"22",
          adaptiveWidth:true,
          adaptiveLabel:"这是一个不定长文本区",
          closeable:false
        },
        {
          color:"Background-Error_Foreground-Error",
          showIcon:true,
          iconPath:"setting_gray_line",
          fixedWidth:false,
          fixedLabel:"22",
          adaptiveWidth:true,
          adaptiveLabel:"这是一个不定长文本区",
          closeable:false
        },
        {
          color:"Background-Tertiary_Foreground-Tertiary",
          showIcon:true,
          iconPath:"setting_gray_line",
          fixedWidth:false,
          fixedLabel:"22",
          adaptiveWidth:true,
          adaptiveLabel:"这是一个不定长文本区",
          closeable:false
        },
        {
          color:"Foreground-Primary_Foreground-Low",
          showIcon:true,
          iconPath:"setting_gray_line",
          fixedWidth:false,
          fixedLabel:"22",
          adaptiveWidth:true,
          adaptiveLabel:"这是一个不定长文本区",
          closeable:false
        },
        {
          color:"Foreground-Secondary_Foreground-Low",
          showIcon:true,
          iconPath:"setting_gray_line",
          fixedWidth:false,
          fixedLabel:"22",
          adaptiveWidth:true,
          adaptiveLabel:"这是一个不定长文本区",
          closeable:false
        },
        {
          color:"Foreground-Error_Foreground-Low",
          showIcon:true,
          iconPath:"setting_gray_line",
          fixedWidth:false,
          fixedLabel:"22",
          adaptiveWidth:true,
          adaptiveLabel:"这是一个不定长文本区",
          closeable:false
        },
        {
          color:"Foreground-Tertiary_Foreground-Low",
          showIcon:true,
          iconPath:"setting_gray_line",
          fixedWidth:false,
          fixedLabel:"22",
          adaptiveWidth:true,
          adaptiveLabel:"这是一个不定长文本区",
          closeable:false
        },
        // 图标false 固定宽度false 自适应宽度true  关闭false
        {
          color:"Background-Medium_Foreground-High",
          showIcon:false,
          iconPath:"setting_gray_line",
          fixedWidth:false,
          fixedLabel:"22",
          adaptiveWidth:true,
          adaptiveLabel:"这是一个不定长文本区",
          closeable:false
        },
        {
          color:"Background-Medium_Foreground-Medium",
          showIcon:false,
          iconPath:"setting_gray_line",
          fixedWidth:false,
          fixedLabel:"22",
          adaptiveWidth:true,
          adaptiveLabel:"这是一个不定长文本区",
          closeable:false
        },
        {
          color:"Foreground-Primary_Foreground-Low",
          showIcon:false,
          iconPath:"setting_gray_line",
          fixedWidth:false,
          fixedLabel:"22",
          adaptiveWidth:true,
          adaptiveLabel:"这是一个不定长文本区",
          closeable:false
        },
        {
          color:"Background-Secondary_Foreground-Secondary",
          showIcon:false,
          iconPath:"setting_gray_line",
          fixedWidth:false,
          fixedLabel:"22",
          adaptiveWidth:true,
          adaptiveLabel:"这是一个不定长文本区",
          closeable:false
        },
        {
          color:"Background-Error_Foreground-Error",
          showIcon:false,
          iconPath:"setting_gray_line",
          fixedWidth:false,
          fixedLabel:"22",
          adaptiveWidth:true,
          adaptiveLabel:"这是一个不定长文本区",
          closeable:false
        },
        {
          color:"Background-Tertiary_Foreground-Tertiary",
          showIcon:false,
          iconPath:"setting_gray_line",
          fixedWidth:false,
          fixedLabel:"22",
          adaptiveWidth:true,
          adaptiveLabel:"这是一个不定长文本区",
          closeable:false
        },
        {
          color:"Foreground-Primary_Foreground-Low",
          showIcon:false,
          iconPath:"setting_gray_line",
          fixedWidth:false,
          fixedLabel:"22",
          adaptiveWidth:true,
          adaptiveLabel:"这是一个不定长文本区",
          closeable:false
        },
        {
          color:"Foreground-Secondary_Foreground-Low",
          showIcon:false,
          iconPath:"setting_gray_line",
          fixedWidth:false,
          fixedLabel:"22",
          adaptiveWidth:true,
          adaptiveLabel:"这是一个不定长文本区",
          closeable:false
        },
        {
          color:"Foreground-Error_Foreground-Low",
          showIcon:false,
          iconPath:"setting_gray_line",
          fixedWidth:false,
          fixedLabel:"22",
          adaptiveWidth:true,
          adaptiveLabel:"这是一个不定长文本区",
          closeable:false
        },
        {
          color:"Foreground-Tertiary_Foreground-Low",
          showIcon:false,
          iconPath:"setting_gray_line",
          fixedWidth:false,
          fixedLabel:"22",
          adaptiveWidth:true,
          adaptiveLabel:"这是一个不定长文本区",
          closeable:false
        },
      ],
      "icon":[
        {
          color:"Background-Medium_Foreground-High",
          showIcon:true,
          iconPath:"setting_gray_line",
          fixedWidth:false,
          fixedLabel:"22",
          adaptiveWidth:false,
          adaptiveLabel:"这是一个不定长文本区",
          closeable:false
        },
        {
          color:"Background-Medium_Foreground-Medium",
          showIcon:true,
          iconPath:"setting_gray_line",
          fixedWidth:false,
          fixedLabel:"22",
          adaptiveWidth:false,
          adaptiveLabel:"这是一个不定长文本区",
          closeable:false
        },
        {
          color:"Background-Primary_Foreground-Primary",
          showIcon:true,
          iconPath:"setting_gray_line",
          fixedWidth:false,
          fixedLabel:"22",
          adaptiveWidth:false,
          adaptiveLabel:"这是一个不定长文本区",
          closeable:false
        },
        {
          color:"Background-Secondary_Foreground-Secondary",
          showIcon:true,
          iconPath:"setting_gray_line",
          fixedWidth:false,
          fixedLabel:"22",
          adaptiveWidth:false,
          adaptiveLabel:"这是一个不定长文本区",
          closeable:false
        },
        {
          color:"Background-Error_Foreground-Error",
          showIcon:true,
          iconPath:"setting_gray_line",
          fixedWidth:false,
          fixedLabel:"22",
          adaptiveWidth:false,
          adaptiveLabel:"这是一个不定长文本区",
          closeable:false
        },
        {
          color:"Background-Tertiary_Foreground-Tertiary",
          showIcon:true,
          iconPath:"setting_gray_line",
          fixedWidth:false,
          fixedLabel:"22",
          adaptiveWidth:false,
          adaptiveLabel:"这是一个不定长文本区",
          closeable:false
        },
        {
          color:"Foreground-Primary_Foreground-Low",
          showIcon:true,
          iconPath:"setting_gray_line",
          fixedWidth:false,
          fixedLabel:"22",
          adaptiveWidth:false,
          adaptiveLabel:"这是一个不定长文本区",
          closeable:false
        },
        {
          color:"Foreground-Secondary_Foreground-Low",
          showIcon:true,
          iconPath:"setting_gray_line",
          fixedWidth:false,
          fixedLabel:"22",
          adaptiveWidth:false,
          adaptiveLabel:"这是一个不定长文本区",
          closeable:false
        },
        {
          color:"Foreground-Error_Foreground-Low",
          showIcon:true,
          iconPath:"setting_gray_line",
          fixedWidth:false,
          fixedLabel:"22",
          adaptiveWidth:false,
          adaptiveLabel:"这是一个不定长文本区",
          closeable:false
        },
        {
          color:"Foreground-Tertiary_Foreground-Low",
          showIcon:true,
          iconPath:"setting_gray_line",
          fixedWidth:false,
          fixedLabel:"22",
          adaptiveWidth:false,
          adaptiveLabel:"这是一个不定长文本区",
          closeable:false
        },
      ]
    }
  },

  /**
   * 生命周期函数--监听页面加载
   */
  onLoad() {

  },

  /**
   * 生命周期函数--监听页面初次渲染完成
   */
  onReady() {

  },

  /**
   * 生命周期函数--监听页面显示
   */
  onShow() {

  },

  /**
   * 生命周期函数--监听页面隐藏
   */
  onHide() {

  },

  /**
   * 生命周期函数--监听页面卸载
   */
  onUnload() {

  },

  /**
   * 页面相关事件处理函数--监听用户下拉动作
   */
  onPullDownRefresh() {

  },

  /**
   * 页面上拉触底事件的处理函数
   */
  onReachBottom() {

  },

  /**
   * 用户点击右上角分享
   */
  onShareAppMessage() {

  }
})